# SPDX-License-Identifier: Apache-2.0

name: test

on:
  push:
    branches: [ 'main' ]
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf # v1
        with:
          swift-version: "5.8"
      - uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1
        with:
          toolchain: stable
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3
        with:
          go-version: 1.19
          check-latest: true
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 10.5.0
      - name: Setup Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 #v4
        with:
          python-version: '3.11.4'
      - name: Setup poetry
        uses: abatilo/actions-poetry@192395c0d10c082a7c62294ab5d9a9de40e48974 #v2
        with:
          poetry-version: '1.5.1'
      - name: Install dependencies with poetry
        working-directory: 'pip/poetry/testdata'
        run: poetry install
      - name: Install dependencies with npm
        working-directory: 'npm/test'
        run: npm install
      - name: Install dependencies with yarn
        uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b # v4
        with:
          cmd: install
          dir: 'yarn/test'
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16.14.0
      - name: Install dependencies with pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - cwd: 'pnpm/test'
          package_json_file: 'pnpm/test/package.json'
      - name: Run swift build
        working-directory: 'swift/test'
        run: swift build

      - run: go test -v ./...
